ninetynine/urls.py
__author__ = 'jason.a.parent@gmail.com (Jason Parent)'

# Django imports...
from django.conf.urls import patterns
from django.conf.urls import url

urlpatterns = patterns('ninetynine.views',
    url(r'^home/$', 'home', name='home'),
    url(r'^game/$', 'game', name='game'),
)

strangedeck/urls.py
__author__ = 'jason.a.parent@gmail.com (Jason Parent)'

# Django imports...
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'strangedeck.views.home', name='home'),
    url(r'^sign_up/$', 'strangedeck.views.sign_up', name='sign_up'),
    url(r'^log_out/$', 'strangedeck.views.log_out', name='log_out'),
    url(r'^ninetynine/', include('ninetynine.urls', namespace='ninetynine')),
    url(r'^admin/', include(admin.site.urls)),
)

ninetynine/models.py
from django.db import models

# Create your models here.

strangedeck/forms.py
__author__ = 'jason.parent@carneylabs.com (Jason Parent)'

# Django imports...
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm

User = get_user_model()


class BootstrapMixin(object):
    def __init__(self, use_bootstrap=True, *args, **kwargs):
        super(BootstrapMixin, self).__init__(*args, **kwargs)

        if use_bootstrap:
            for key in self.fields:
                self.fields[key].widget.attrs.update({
                    'class': 'form-control'
                })


class SignUpForm(BootstrapMixin, forms.ModelForm):
    error_messages = {
        'duplicate_email': 'A user with that email already exists.',
        'password_mismatch': 'The two password fields didn\'t match.'
    }

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password Confirmation',
        widget=forms.PasswordInput,
        help_text='Enter your password again.'
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def clean_email(self):
        email = self.cleaned_data['email']

        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email

        raise forms.ValidationError(
            self.error_messages['duplicate_email'],
            code='duplicate_email'
        )

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )

        return password2

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.username = self.cleaned_data['email']
        user.set_password(self.cleaned_data['password1'])

        if commit:
            user.save()

        return user


class LogInForm(BootstrapMixin, AuthenticationForm):
    pass

ninetynine/views.py
__author__ = 'jason.a.parent@gmail (Jason Parent)'

# Django imports...
from django.shortcuts import render


def home(request):
    return render(request, 'ninetynine/home.html')


def game(request):
    return render(request, 'ninetynine/game.html')

strangedeck/views.py
__author__ = 'jason.parent@carneylabs.com (Jason Parent)'

# Django imports...
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.shortcuts import render

# Local imports...
from .forms import LogInForm
from .forms import SignUpForm


def sign_up(request):
    form = SignUpForm()

    if request.method == 'POST':
        form = SignUpForm(data=request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data['email']
            password = form.cleaned_data['password1']

            # Log in new user...
            return log_in(request, username, password)

    return render(request, 'strangedeck/sign_up.html', {
        'form': form
    })


def log_in(request, username, password):
    user = authenticate(username=username, password=password)

    if user is not None:
        if user.is_active:
            login(request, user)
        else:
            messages.error(request, 'Account disabled.')

    else:
        messages.error(request, 'Invalid login.')

    return redirect(reverse('home', current_app='strangedeck'))


@login_required
def log_out(request):
    logout(request)

    return redirect(reverse('home', current_app='strangedeck'))


def home(request):
    if request.user.is_authenticated():
        return render(request, 'strangedeck/home.html')

    else:
        form = LogInForm(request)

        if request.method == 'POST':
            form = LogInForm(data=request.POST)

            if form.is_valid():
                login(request, form.get_user())
            else:
                messages.error(request, 'Invalid login.')

            return redirect(reverse('home', current_app='strangedeck'))

        return render(request, 'strangedeck/log_in.html', {
            'form': form
        })

ninetynine/templates/ninetynine/game.html
{% extends 'strangedeck/base.html' %}

{% block page-styles %}
	<link href="/static/strangedeck/css/magic.min.css" rel="stylesheet">
	<link href="/static/ninetynine/css/styles.css" rel="stylesheet">
	<link href="/static/ninetynine/css/deck.css" rel="stylesheet">

	<style>
		.magictime.slideLeftRetourn,
		.magictime.slideRightRetourn 
		{
			-webkit-animation-duration: 0.25s;
			-moz-animation-duration: 0.25s;
			-o-animation-duration: 0.25s;
			animation-duration: 0.25s;
		}
	</style>
{% endblock page-styles %}

{% block page-modals %}
	<div id="game-over-modal" class="modal fade">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-body">
					<img id="winner-img" class="media-object img-circle modal-image">
					<p id="winner-name">Nina Craig Wins!</p>
					<button class="btn btn-primary" type="button" data-dismiss="modal">Continue</button>
				</div>
			</div>
		</div>
	</div>
{% endblock page-modals %}

{% block page-content %}
	<div class="container">
		<!-- Computer -->
		<div class="col-md-3">
			<div id="player1-panel" class="panel panel-default player-panel">
				<div class="panel-body">
					<div class="media">
						<div class="media-body">
							<h4 class="media-heading"></h4>
							Wins: 0
						</div>
						<div class="media-right">
							<a href="#">
								<img class="media-object img-circle panel-image">
							</a>
						</div>
					</div>
					<div class="hand"></div>
				</div>
			</div>
		</div>

		<!-- Piles -->
		<div class="col-md-6">
			<div id="piles">
				<div id="draw-pile" class="card card-back card-blue"></div>
				<div id="score-display">
					<div>
						<p>Score</p>
						<p id="score-text">0</p>
					</div>
				</div>
				<div id="play-pile" class="card">
					<div id="bottom-card" class="card"></div>
					<div id="top-card" class="card"></div>
				</div>
			</div>
		</div>

		<!-- Player -->
		<div class="col-md-3">
			<div id="player2-panel" class="panel panel-default player-panel">
				<div class="panel-body">
					<div class="media">
						<div class="media-left">
							<a href="#">
								<img class="media-object img-circle panel-image">
							</a>
						</div>
						<div class="media-body" style="text-align: right;">
							<h4 class="media-heading"></h4>
							Wins: 0
						</div>
					</div>
					<div class="hand"></div>
				</div>
			</div>
		</div>
	</div>
{% endblock page-content %}

{% block page-scripts %}
	<script src="/static/ninetynine/js/deck.js"></script>
	<script src="/static/ninetynine/js/game.js"></script>
	<script src="/static/ninetynine/js/ninetynine.js"></script>
{% endblock page-scripts %}

ninetynine/templates/ninetynine/home.html
{% extends 'strangedeck/base.html' %}

{% block page-styles %}
    <style>
        body {
            padding-top: 100px;
        }
    </style>
{% endblock %}

{% block page-content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Multiplayer</h4>
            </div>
            <div class="list-group">
                <a class="list-group-item" href="{% url 'ninetynine:game' %}">Join Game</a>
                <a class="list-group-item" href="{% url 'ninetynine:game' %}">Host Game</a>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Single Player</h4>
            </div>
            <div class="list-group">
                <a class="list-group-item" href="{% url 'ninetynine:game' %}">Play Game</a>
            </div>
        </div>
    </div>
{% endblock page-content %}

ninetynine/templates/ninetynine/home_ng.html
<!doctype html>

<html ng-app="ninetynine">

<head>
	<meta charset="utf-8">
	<title>Strange Deck</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<link href="/static/strangedeck/css/flatly.min.css" rel="stylesheet" media="screen">
	<link href="/static/strangedeck/css/magic.min.css" rel="stylesheet" media="screen">
	<link href="/static/ninetynine/css/styles.css" rel="stylesheet" media="screen">
	<link href="/static/ninetynine/css/deck.css" rel="stylesheet" media="screen">

	<style>
		.magictime.slideLeftRetourn,
		.magictime.slideRightRetourn
		{
			-webkit-animation-duration: 0.25s;
			-moz-animation-duration: 0.25s;
			-o-animation-duration: 0.25s;
			animation-duration: 0.25s;
		}
	</style>
</head>

<body ng-controller="NinetynineController">
    {% verbatim %}
        <div id="game-over-modal" class="modal fade">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-body">
                        <img id="winner-img"
                             class="media-object img-circle modal-image"
                             ng-src="{{ data.game.winner.photo }}">
                        <p id="winner-name">{{ data.game.winner.name }} Wins!</p>
                        <button class="btn btn-primary" type="button" data-dismiss="modal">Continue</button>
                    </div>
                </div>
            </div>
        </div>
    {% endverbatim %}

	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button class="navbar-toggle collapsed"
						type="button"
						data-toggle="collapse"
						data-target="#navbar-content">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">STRANGE DECK</a>
			</div>
			<div id="navbar-content" class="collapse navbar-collapse">
				<ul class="nav navbar-nav">

				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		<!-- Computer -->
        {% verbatim %}
            <div class="col-md-3">
                <div id="player1-panel" class="panel panel-default player-panel">
                    <div class="panel-body">
                        <div class="media">
                            <div class="media-body">
                                <h4 class="media-heading"
                                    ng-bind="data.game.players[0].name"></h4>
                                Wins: 0
                            </div>
                            <div class="media-right">
                                <a href="#">
                                    <img class="media-object img-circle panel-image"
                                         ng-src="{{ data.game.players[0].photo }}">
                                </a>
                            </div>
                        </div>
                        <div class="hand"></div>
                    </div>
                </div>
            </div>
		{% endverbatim %}

		<!-- Piles -->
		<div class="col-md-6">
			<div id="piles">
				<div id="draw-pile" class="card card-back card-blue"></div>
				<div id="score-display">
					<div>
						<p>Score</p>
						<p id="score-text">0</p>
					</div>
				</div>
				<div id="play-pile" class="card">
					<div id="bottom-card" class="card"></div>
					<div id="top-card" class="card"></div>
				</div>
			</div>
		</div>

		<!-- Player -->
        {% verbatim %}
            <div class="col-md-3">
                <div id="player2-panel" class="panel panel-default player-panel">
                    <div class="panel-body">
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img class="media-object img-circle panel-image"
                                         ng-src="{{ data.game.players[1].photo }}">
                                </a>
                            </div>
                            <div class="media-body" style="text-align: right;">
                                <h4 class="media-heading" ng-bind="data.game.players[1].name"></h4>
                                Wins: 0
                            </div>
                        </div>
                        <div class="hand"></div>
                    </div>
                </div>
            </div>
		{% endverbatim %}
	</div>

	<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.12/angular.min.js"></script>
	<script src="/static/ninetynine/js/deck.js"></script>
	<script src="/static/ninetynine/js/game.js"></script>
    <script src="/static/ninetynine/angular/app.js"></script>
</body>

</html>

strangedeck/templates/strangedeck/base.html
<!doctype html>

<html>

<head lang="en">
    <meta charset="utf-8">
    <title>{% block page-title %}Strange Deck{% endblock page-title %}</title>
    <meta name="viewport"
          content="user-scalable=no, width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/strangedeck/css/flatly.min.css" rel="stylesheet">

    {% block page-styles %}{% endblock page-styles %}
</head>

<body>
    {% block page-modals %}{% endblock page-modals %}

    <nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button class="navbar-toggle collapsed"
						type="button"
						data-toggle="collapse"
						data-target="#navbar-content">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'home' %}">STRANGE DECK</a>
			</div>
			<div id="navbar-content" class="collapse navbar-collapse">
				{% if user.is_authenticated %}
                    <div class="navbar-right">
                        <p class="navbar-text">Signed in as {{ user.first_name|capfirst }}</p>
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                                   <span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{% url 'members:log_out' %}">Log Out</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                {% else %}
                    <p class="navbar-text navbar-right">
                        <a class="navbar-link" href="{% url 'home' %}">Log In</a> or
                        <a class="navbar-link" href="{% url 'sign_up' %}">Sign Up</a>
                    </p>
                {% endif %}
			</div>
		</div>
	</nav>

    {% block page-content %}
        <div class="container">
            <div class="list-group">
                <a class="list-group-item" href="{% url 'ninetynine:home' %}">Ninety-nine</a>
            </div>
        </div>
    {% endblock page-content %}

    <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

    {% block page-scripts %}{% endblock page-scripts %}
</body>

</html>

strangedeck/templates/strangedeck/home.html
{% extends 'strangedeck/base.html' %}

{% block page-styles %}
    <style>
        body {
            padding-top: 100px;
        }
    </style>
{% endblock %}

{% block page-content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Games</h4>
            </div>
            <div class="list-group">
                <a class="list-group-item" href="{% url 'ninetynine:home' %}">Ninety-nine</a>
            </div>
        </div>
    </div>
{% endblock page-content %}

strangedeck/templates/strangedeck/log_in.html
{% extends 'strangedeck/base.html' %}

{% block page-styles %}
    <style>
        body {
            padding-top: 100px;
        }
    </style>
{% endblock %}

{% block page-content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
                <div class="jumbotron">
                    <h4>Log in!</h4>
                    <a href="#" class="btn btn-danger btn-block">
                        <i class="fa fa-google-plus"></i>
                    </a>
                    <a href="#" class="btn btn-primary btn-block">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a href="#" class="btn btn-info btn-block">
                        <i class="fa fa-twitter"></i>
                    </a>
                    {% include 'strangedeck/partials/bootstrap_messages.html' %}
                    <form action="{% url 'home' %}" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.errors %}
                                <div class="form-group has-error has-feedback">
                                    {{ field.label_tag }}
                                    {{ field }}
                                    <span class="help-block">
                                        {{ field.errors|join:', ' }}
                                    </span>
                                </div>
                            {% else %}
                                <div class="form-group">
                                    {{ field.label_tag }}
                                    {{ field }}
                                </div>
                            {% endif %}
                        {% endfor %}
                        <button class="btn btn-primary" type="submit">Log In</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock page-content %}

strangedeck/templates/strangedeck/partials/bootstrap_messages.html
{% comment %}
    Make sure you add custom Bootstrap message tags to your settings file. The message tags should
    correspond to the Bootstrap 'alert' component color themes.
{% endcomment %}

{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissable">
        <button class="close" type="button" data-dismiss="alert">&times;</button>
        {{ message|safe }}
    </div>
{% endfor %}

strangedeck/templates/strangedeck/sign_up.html
{% extends 'strangedeck/base.html' %}

{% block page-styles %}
    <style>
        body {
            padding-top: 100px;
        }
    </style>
{% endblock page-styles %}

{% block page-content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
                <div class="jumbotron">
                    <h4>Sign up!</h4>
                    <a href="#" class="btn btn-danger btn-block">
                        <i class="fa fa-google-plus"></i>
                    </a>
                    <a href="#" class="btn btn-primary btn-block">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a href="#" class="btn btn-info btn-block">
                        <i class="fa fa-twitter"></i>
                    </a>
                    {% include 'strangedeck/partials/bootstrap_messages.html' %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <button class="close" type="button" data-dismiss="alert">&times;</button>
                            {{ error|safe }}
                        </div>
                    {% endfor %}
                    <form action="{% url 'sign_up' %}" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.errors %}
                                <div class="form-group has-error has-feedback">
                                    {{ field.label_tag }}
                                    {{ field }}
                                    <span class="help-block">
                                        {{ field.errors|join:', ' }}
                                    </span>
                                </div>
                            {% else %}
                                <div class="form-group">
                                    {{ field.label_tag }}
                                    {{ field }}
                                </div>
                            {% endif %}
                        {% endfor %}
                        <button class="btn btn-primary" type="submit">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock page-content %}